//go:generate oapi-codegen -config .openapi.yaml https://tf-api.roto.lol/openapi-3.0.yaml
package tfapi

import (
	"errors"
	"net/http"
)

var ErrNoResult = errors.New("no results")

// TFAPI provides a trivial interface around the autogenerated tf-api client just to
// make any future api changes a bit easier as its still a bit of a moving target.
type TFAPI struct {
	*ClientWithResponses
}

func New(host string, client *http.Client) (*TFAPI, error) {
	tfapiClient, errClient := NewClientWithResponses(host, WithHTTPClient(client))
	if errClient != nil {
		return nil, errClient
	}

	return &TFAPI{ClientWithResponses: tfapiClient}, nil
}
